export const MAX_NAME_LENGTH=20;
export function cleanDisplayName(value){return String(value??'').trim().replace(/[<>]/g,'').slice(0,MAX_NAME_LENGTH);}
export function onlineModeKey(game,settings={}){if(game==='match')return `count:${Number(settings.count)||20}`;if(game==='math')return `${settings.operation||'mul'}:${settings.difficulty||'easy'}`;if(['mine','sudoku'].includes(game))return settings.difficulty||'easy';if(game==='baseball')return `length:${Number(settings.length)||3}`;if(game==='gomoku')return 'ai:standard';return 'default';}
export function onlineScore(game,score,record={},settings={}){if(record.result==='lost'||record.result==='early'||game==='tictactoe')return null;if(game==='gomoku'&&(settings.mode!=='ai'||record.winner!==settings.playerStone))return null;const metrics={match:record.moves,math:score,mine:record.elapsed,tensec:Math.abs(10000-record.elapsed),gomoku:1,baseball:record.tries,sudoku:record.elapsed,reaction:record.elapsed,game2048:score};const metric=Number(metrics[game]);if(!Number.isFinite(metric))return null;return {game,mode:onlineModeKey(game,settings),score:metric,aux:{...record}};}
export const isHigherBetter=(game)=>['math','gomoku','game2048'].includes(game);
export function isBetterScore(game,current,candidate){if(current==null)return true;return isHigherBetter(game)?candidate>current:candidate<current;}
export const onlineUnavailableMessage=()=> '온라인 랭킹에 연결할 수 없어요.';
const elapsedTie=(row)=>Number(row.aux?.elapsed)||Number.MAX_SAFE_INTEGER;
export function sortLeaderboard(game,rows){return [...rows].sort((a,b)=>(isHigherBetter(game)?b.score-a.score:a.score-b.score)||(['match','baseball'].includes(game)?elapsedTie(a)-elapsedTie(b):0)||String(a.display_name).localeCompare(String(b.display_name),'ko'));}
export function formatOnlineScore(game,row){const value=Number(row.score);if(game==='reaction')return `${value}ms`;if(['mine','sudoku'].includes(game))return `${(value/1000).toFixed(1)}초`;if(game==='tensec')return `오차 ${(value/1000).toFixed(3)}초`;if(game==='match')return `${value}회`;if(game==='baseball')return `${value}회`;if(game==='gomoku')return `${value}승`;if(game==='game2048')return `${value}점`;return `${value}점`;}
