import { createSudokuPuzzle, createSudokuState, inputSudokuNumber, selectSudokuCell } from './sudokuLogic.js';
export function mountSudoku(root,done,{difficulty='easy'}={}) {
  let state=createSudokuState(createSudokuPuzzle(difficulty));const startedAt=Date.now();let reported=false;
  const board=document.createElement('div');board.className='sudoku-board';board.setAttribute('aria-label','9 곱하기 9 스도쿠판');
  const status=document.createElement('p');status.className='sudoku-status';status.setAttribute('role','status');const pad=document.createElement('div');pad.className='sudoku-pad';pad.setAttribute('aria-label','스도쿠 숫자패드');root.append(status,board,pad);
  function finish(){if(reported)return;if(state.gameOver){reported=true;done(0,{result:'lost',mistakes:state.mistakes,difficulty});}else if(state.complete){reported=true;const elapsed=Date.now()-startedAt;done(-elapsed,{elapsed,mistakes:state.mistakes});}}
  function render(){status.textContent=state.message+' · 실수 '+state.mistakes+' / 3';board.replaceChildren(...state.values.map((value,index)=>{const fixed=state.puzzle[index]!=='0';const b=document.createElement('button');b.type='button';b.textContent=value==='0'?'':value;b.disabled=fixed||state.complete||state.gameOver;b.className=(fixed?'sudoku-fixed':'sudoku-cell')+(state.wrong.includes(index)?' is-wrong':'')+(state.selected===index?' is-selected':'');b.setAttribute('aria-label',(Math.floor(index/9)+1)+'행 '+(index%9+1)+'열 '+(fixed?'고정 숫자':'입력 칸')+' '+(value==='0'?'비어 있음':value));b.setAttribute('aria-invalid',String(state.wrong.includes(index)));b.onclick=()=>{state=selectSudokuCell(state,index);render();};return b;}));const counts=state.values.reduce((all,value)=>{all[value]=(all[value]||0)+1;return all;},{});pad.replaceChildren(...Array.from({length:9},(_,i)=>{const number=i+1,b=document.createElement('button');b.type='button';b.textContent=number;b.disabled=state.gameOver||state.complete||counts[number]>=9;b.setAttribute('aria-label',number+' 입력'+(counts[number]>=9?' 완료':''));b.onclick=()=>{state=inputSudokuNumber(state,number);render();finish();};return b;}));}
  render();return()=>{state={...state,complete:true};};
}
